### ISSUE TITLE
Bug if the chunk split inside an UTF-8 (or other encoding) character

### ISSUE THREAD

**Issue by jersou** [masataka/xmlp#1]
For information : https://github.com/denoland/deno/issues/14507

My workaround : 
```
- parser.parse(stream);  
+ stream
+    .pipeThrough(new TextDecoderStream(encoding))
+    .pipeTo(new WritableStream({ write: (str) => parser.parse(str) }));
```

That said, thank you for this lib ! And for option 'string' in the parse() method that permit this workaround :-)

**Comment by masataka** [comment]
@jersou 

Thank you for letting me know the issue.
When I created this library, TextDecoderStream wasn't provided, so I didn't know a good way to resolve the encoding with a stream, which is a good solution. and ... I found "Deno.copy" was deprecated. 
I will try to solve them non-destructively.

I was born in the double-byte area, but I'm embarrassed to cut corners in encoding.

**Comment by masataka** [comment]
@jersou 

Please check v0.3.0.

**Comment by jersou** [comment]
:+1: the v0.3.0 fix this bug, Thanks !
